### PR TITLE
Zulu trait text update

### PR DESCRIPTION
**Pull request by EricB1**
The Zulu trait gives half maintenance costs for melee and vanguard
units.  The text left out the part about vanguards.  Added it in.

### CODE REVIEW

**Comment by stackpoint** [comment]
Does the vanguard line still exist?

**Comment by GrantSP** [comment]
Yes and no.
It basically is the name given in the mod to **UNITCOMBAT_RECON**.
There are tables that use the term and there some promotions relating to "vanguard", but yes it would be safe to say **vanguards** don't exist.

**Comment by stackpoint** [comment]
But the distinction between UNITCOMBAT_MELEE and UNITCOMBAT_RECON exists? So since the Zulu has the added modifier on UNITCOMBAT_RECON units, we should make that clear.

**Comment by GrantSP** [comment]
Okay so with the exception of the machine gun, gatling gun & bazooka all
the RECON units are in fact MELEE.

Wasn't up to speed on what we changed for the Zulu.

Do the Zulu really need to be working their trait on those units? I
wouldn't have thought so. Maybe we should look at why those three units are
called RECON.

I can see the need to add the CLASS to the trait but as the distinction by
and large is a minor one that made me ask my question.

On 19 February 2014 15:30, stackpointer notifications@github.com wrote:

> But the distinction between UNITCOMBAT_MELEE and UNITCOMBAT_RECON exists?
> So since the Zulu has the added modifier on UNITCOMBAT_RECON units, we
> should make that clear.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/pull/197#issuecomment-35465214
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Pull request merged**
