### PR TITLE
Policy Changes

### PR DESCRIPTION
**Pull request by EricB1**
Several minor policy changes.  Most affect the Wealth tree.  Change to the Piety opener to have the effect many people agreed upon in the forum.  Couple of minor typo fixes with the Representation policy and the Maritime Infrastructure policy.  Weakened the Wealth opener and the Protectionism policies.  Strengthened the Caravans policy and the Entrepreneurship policy.

All of these changes I've been using for a while and they work without bugs.

### CODE REVIEW

**Comment by Apuity** [comment]
For Representation, did you mean the ExtraHappiness="1" line? 

I thought that was designed for the capital. Because the Capital is always connected, so there is +1 National Happiness specifically for the capital.  I don't think that is +1 Happiness per city..?

**Comment by EricB1** [comment]
Yeah I believe that is correct.  I was testing this out to see what it does and you are right.

**Comment by EricB1** [comment]
I checked a bit closer on the Representation policy.  I'm playing a game right now.  I have built 3 cities (capital and 2 others).  1 city is connected to the capital.  1 is not.  Before connecting to the capital, I selected the representation policy.  It gave -5% unhappiness from population, which in effect gave me +1 happiness.  It also gave +1 national happiness in the capital.

When I connected that first city, I got an extra +2 national happiness.  It says "+2 national happiness from city connections" even though I only have 1 city connected.  I remember playing last week too where I had 9 cities connected and it would say "+18 national happiness from city connections"  I'm pretty sure that the mod code is piling on top of the vanilla code.

The vanilla code for Meritocracy gives +1 happiness per city connection.  The mod code for Representation does the same thing.  Also the vanilla code for Representation gives a policy discount for the number of cities, while the mod code for Meritocracy does this too.  That effect is also being compounded.  If we don't want it to do this, then the mod code for Meritocracy and for Representation need to be edited as that code isn't removing the old vanilla effects of the policies.

**Comment by EricB1** [comment]
I was slightly off on that previous comment.  Actually the meritocracy policy is giving +1 happiness per city connection.  The representation policy gives another +1 happiness per city connection.  So I was correct in finding +2 happiness per city connection, just incorrect about the source of it.  Also, I encountered that both policies are giving culture cost discounts per city, which is probably unintended.  That last commit just updates the text to accurate describe what the policies are currently doing.  I can fix them if you give the word that it's really not designed to do this.  Not sure what the original design is though.

**Comment by skodkim** [comment]
I made a fix for Metoticracy unintentionally giving happiness for connected cities here:
here: https://github.com/Thalassicus/cep-bnw/pull/164

Don't think it's been released yet.

\Skodkim

**Comment by EricB1** [comment]
You should also correct Representation unintentionally giving culture bonuses.

**Comment by skodkim** [comment]
Where do you see Representation giving Culture bonusses?

Edit: You mean that the vanilla NumCitiesPolicyCostDiscount hasn't been removed from Representation?

\Skodkim

**Comment by skodkim** [comment]
I'm confiden't the extra happiness and policy discount it a mistake so I've made a fix here: https://github.com/Thalassicus/cep-bnw/commit/9ebf6995c6db7bc9c6cf655c0df31fd93c4ee0d2

You should retract your text change for the policy.

\Skodkim

**Pull request merged**
