### PR TITLE
Additions to 3.13

### PR DESCRIPTION
**Pull request by skodkim**
Units upgrade to Swordsman and Composite Bowman with Renowned Warrior/Archer stories (may already be in?)
Unit upgrades is now 2 times production difference as intended
Walls now have 25% conquest propability as intended
Removed resouce requirements for Gatling Guns, Bazooka and Machine Guns as intended
Ceremonial Rites now give +1 culture/cultural Building as intended

### CODE REVIEW

**Comment by stackpoint** [comment]
Looks like you weren't able to merge the branches together and this has merge conflicts. I don't know how to use the command line to fix this so I'll add your changes in manually, with all due credit to you of course.

**Comment by stackpoint** [comment]
All the changes should be committed.

**Comment by stackpoint** [comment]
I modified your tradition code to fit the format of code that deals with it. See https://github.com/Thalassicus/cep-bnw/commit/d98ba2d4c75e22e5845d5e58e3f25803c2a99c72

**Comment by skodkim** [comment]
Thanks for the help. As said before I feel like a real newb at this and I had a weak suspicion I was working on a old copy, which may be the reason the branches couldn't be merged (version 3.13 said 3.12.2 in modinfo).

Is there any way of sending private messages ti other users using the Github or should we use e.g. CivFanatics for "private messages"?

\Skodkim

**Comment by stackpoint** [comment]
I don't think private messages are possible here. Probably all done through email. I sent you a PM through civfanatics.

**Pull request closed without merging**
