### PR TITLE
Arabian Text Trait Bug Fix

### PR DESCRIPTION
**Pull request by EricB1**
The Text for the Arabian trait is called
"TXT_KEY_TRAIT_LAND_TRADE_GOLD2" while CEP uses the same thing without
the '2'
This minor fix points the variables of Description and ShortDescription
to the CEP text instead of the vanilla text.

### CODE REVIEW

**Comment by stackpoint** [comment]
@EricB1, you should just work directly on the project now that @Thalassicus has made you a project collaborator.

**Comment by stackpoint** [comment]
You can also merge this pull yourself. Did you modify the google spreadsheet to reflect this text change?

**Comment by EricB1** [comment]
I saw that I had been added as a project collaborator, but I didn't want to put through a change without input from others.  This change is really just a bug fix and doesn't alter the design of the project.  Do those types of changes need to go into the spreadsheet?

**Comment by EricB1** [comment]
I also sent a request to get access to the google docs spreadsheet.  It was blocking me.

**Comment by stackpoint** [comment]
Follow the instructions here to join the group: https://github.com/Thalassicus/cep-bnw/issues/6#issuecomment-28624815

**Comment by stackpoint** [comment]
I misread your commit message. Did you update the policy text in the spreadsheets? And the tech path? I believe you modified both in previous merges.

**Comment by stackpoint** [comment]
And there shouldn't be a problem with bug fixing like this and @Thalassicus has given you project permissions.

**Comment by EricB1** [comment]
Okay I updated the spreadsheet for the policy changes and also for the tech prereq change.  I didn't update anything for the small bug fix to Arabia as there's no spreadsheet data for something like that.

**Comment by stackpoint** [comment]
Yeah, I thought the error was in the text itself instead of the name.

**Comment by GrantSP** [comment]
Shouldn't a bugfix like this be added to the stable branch?
It isn't really a "new" feature.

**Pull request merged**
