### PR TITLE
fix civilopedia crash in xml as well #112

### PR DESCRIPTION
**Pull request by saulshanabrook**

### CODE REVIEW

**Comment by GrantSP** [comment]
Hmm... find a bug, fix a bug.

**Comment by saulshanabrook** [comment]
Maybe this shouldn't be merged. I don't have BNW, so this crash might just be because of that.

**Comment by GrantSP** [comment]
We'll soon find out. Makes sense though. The lua & xml both refer to the World Congress, which is a BNW feature, so if we can avoid conflicts with extension dependencies that's good.
At any rate it is any easy thing to remove.

So you are on a Mac without BNW? All this is good to know. The wider the user base differences, the better.

**Comment by ghost** [comment]
i have a Mac and BNW and I do not experience this crash.

**Comment by stackpoint** [comment]
This "fix" needs to be reverted. The cause of his bug was because he did not own BNW. This xml change would revert the world congress button graphic back to the old help button graphic.

As an aside, I also believe that the MAC version of civ 5 may be (still?) a couple hotfixes behind the windows version.

**Comment by ghost** [comment]
The Steam Version for the MAC is up to date with the PC version.  I think the App Store version is as well but not for sure.

**Pull request merged**
