### PR TITLE
Removed unintended tweak to GP

### PR DESCRIPTION
**Pull request by skodkim**
At present the update statement did nothing as no specialists had
YIELD_CULTURE in the SpecialistYields table but it could have caused
future bugs. If the intention was to tweak culture from writers, musicians and artists use CulturePerTurn from the Specialists table.

### CODE REVIEW

**Comment by stackpoint** [comment]
I just double checked the SpecialistYields table and it looks like the artist, writers, and musicians are added in there with CEP.

There seems to be code [here](https://github.com/Thalassicus/cep-bnw/blob/stable/Cat/Cat/Tools/YieldLibrary/YL_Data.sql) that moves the CulturePerTurn into the SpecialistYields table but I can't be sure. This information could be used in the YieldLibrary even though it doesn't actually grant the actual culture itself. Not sure if this code should be removed or not.

**Comment by stackpoint** [comment]
Hmm, it doesn't seem like the SpecialistYields table is used anywhere in the mod: https://github.com/Thalassicus/cep-bnw/search?q=specialistyields&type=Code

Except for YieldFlavors...

**Comment by skodkim** [comment]
Weird. Maybe thats what is causing a display bug where +3 culture is displayed twice on e.g. a writer specialist in the city view.

Better not remove it then even though all three specialist give 3 culture to begin with (as far as I recall).

Edit: written before your last post

\skodkim

**Comment by stackpoint** [comment]
Hm, that would explain the display issue. Maybe removing that would solve it.

**Comment by skodkim** [comment]
Actually my change doesn't remove the display problem (it is only display though).

What removes it is commenting out the following lines in YL_Data.sql:

INSERT INTO SpecialistYields(SpecialistType, YieldType, Yield)
SELECT Type, 'YIELD_CULTURE', CulturePerTurn
FROM Specialists WHERE CulturePerTurn <> 0;

This has no effect on yields in the game, e.g. you still get 3 culture from writers, etc.

Unfortunately this seems to be a poor solution due to the way flavors are assigned (only uses the SpecialistYields and not the CulturePerTurn field) so perhaps we should just accept the display error as it is and forget my commit.

\Skodkim

**Comment by stackpoint** [comment]
I'll take a look at the flavors sql, it should be possible to assign flavor values for positive values of CPT. I'll merge this in once I figure it out.

**Comment by stackpoint** [comment]
I took a closer look at the flavor code and it seems like it never triggers. Instead, the following code is used to give flavor values to the specialists.

``` sql
INSERT INTO SpecialistFlavors (SpecialistType, FlavorType, Flavor)
        SELECT spec.Type, unitFlavor.FlavorType, 8
        FROM Unit_Flavors unitFlavor, UnitClasses class, Specialists spec
        WHERE class.Type = spec.GreatPeopleUnitClass
        AND unitFlavor.UnitType = class.DefaultUnit
        ;
```

I'll merge this and the other discussed change.

**Pull request merged**
