### PR TITLE
Fix for Meritocracy policy

### PR DESCRIPTION
**Pull request by skodkim**
Meritocracy unintentionally gave happiness for connected cities reduced
unhappiness from population in non-Occupied cities

### CODE REVIEW

**Comment by stackpoint** [comment]
You should've pushed this to stable.

**Comment by skodkim** [comment]
Sorry. Pushed it to new features because I saw that was what you were working on.

stackpointer notifications@github.com skrev:

> You should've pushed this to stable.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/pull/164#issuecomment-33439756

## 

Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by stackpoint** [comment]
It's just that I don't know when I'll be able to merge new-features back into stable because of the balance changes.

**Comment by skodkim** [comment]
Should I try to make the commit to stable?

Fra: stackpointer [mailto:notifications@github.com] 
Sendt: 28. januar 2014 06:08
Til: Thalassicus/cep-bnw
Cc: skodkim
Emne: Re: [cep-bnw] Fix for Meritocracy policy (#164)

It's just that I don't know when I'll be able to merge new-features back into stable because of the balance changes.

**Comment by stackpoint** [comment]
That might cause merge errors. I would recommend against it.

**Comment by skodkim** [comment]
Well, on the bright side I found out how not to make commits containing a lot af already committed changes :-)

Guess I should just stick to comitting to stable anyway as I'm not really doing any new Development on the mod anyway - "just" bug fixing and small tweaks.

\Skodkim

**Pull request merged**
