### PR TITLE
Tradition now unlocks Banaue Rice Terraces

### PR DESCRIPTION
**Pull request by skodkim**
The consensus on the forums seems to be that unlocking the Great library
with Tradition is a poor choice and that Banaue Rice Terraces would be
better. I agree. Speadsheet also changed

http://forums.civfanatics.com/showthread.php?t=517804

### CODE REVIEW

**Comment by skodkim** [comment]
It seems an unintended change was also made automatically by my text editor to 'TXT_KEY_POLICY_WAR_EPICS_TEXT'

Since I've updated the spreadsheet too this is irrelevant, right?

\Skodkim

**Comment by stackpoint** [comment]
Although the spreadsheet wasn't updated with your unintended change, this is a problem because it seems like your text editor replaced the "Ancient Greek adjective ἐπικός (epikos), from ἔπος (epos)" with ???.

If you can't revert that change, I can do it myself. What text editor are you using? Or it could be that your computer/region (Denmark right?) doesn't have Greek characters?

**Comment by stackpoint** [comment]
I also saw that you said you modified the spreadsheets, but you modified both the spreadsheet for the text description and the code generation for the CEP_WonderUnlocks.sql file?

``` sql
-- CEP_WonderUnlocks.sql created by Wonder_Unlocks tab of Wonders spreadsheet:
-- https://drive.google.com/folderview?id=0B58Ehya83q19eVlvWXdmLXZ6UUE
```

**Comment by stackpoint** [comment]
Nevermind. No reason I couldn't fix the Greek myself.

**Comment by stackpoint** [comment]
Hm, when I tried to paste the Greek letters into Notepad++ I got a bunch of ?? so I guess it's not a region problem. But I fixed it anyway here: https://github.com/Thalassicus/cep-bnw/commit/f51685ef3a9ffb7b993276bc03e26f6c73d0cfe0

**Comment by skodkim** [comment]
Sorry for all the fuss! Did you get it all fixed in the end?

I Use Textpad which is normally a realy good text editor. Text files from CEP always seem to give me problems with latin letters though.

I wasn't aware that there was a spreadsheet generating the Wonder unlocks. Just opened the sql and toced that it says so in the first line - I'll pay more attention in the future!

\Skodkim

**Comment by stackpoint** [comment]
I fixed the greek text but haven't updated any spreadsheets. It might be an encoding problem since notepad++ ate the text too.

**Comment by skodkim** [comment]
Just updated the spreadsheet.

\Skodkim

**Comment by stackpoint** [comment]
I just tested the game with the latest build and I just realized that the Rice Terraces unlocks at Engineering. Which is extremely late for an Ancient Era Policy Tree.

**Comment by skodkim** [comment]
I've played with this for a while and haven't found it a problem. IMHO It would be far worse the other way around.

\Skodkim

**Comment by stackpoint** [comment]
Right, but the other ancient era trees get a wonder they can build in the ancient era.

**Comment by skodkim** [comment]
Terracotta Army has also been suggested. It's a bit earlier isn't it?

\Skodkim

**Comment by stackpoint** [comment]
Terracotta Army is the liberty opener. And we still need to find/make an honor replacement.

**Pull request merged**
