### PR TITLE
Wealth Tree policy changes

### PR DESCRIPTION
**Pull request by EricB1**
Changed Caravans policy from +2 gold to +3 gold per trade route.

### CODE REVIEW

**Comment by EricB1** [comment]
Sorry, Didn't mean to add this as an issue.  Still learning how to use Github.

**Comment by GrantSP** [comment]
Nice work @EricB1 although at the moment we are putting all these changes into the new-features branch. I probably wasn't as clear as I could have been in explaining that.
This commit you have pushed is aimed at the Stable branch.

There is a way to easily change that, just not sure at the moment.

**Comment by EricB1** [comment]
I figured that new features was for major changes and stable was for minor changes.  If new features is for any changes, then what goes in stable?

**Comment by GrantSP** [comment]
Not a problem. Don't worry about it.
Still it is a good chance to recall what I said about being sure of which branch you are on.

Not your fault BTW. Mine. Should have been more explicit.

**Comment by stackpoint** [comment]
If you aren't given project permissions as a collaborator, then all your pull requests will appear as an issue for a collaborator to merge into the project.

["If you have time, pick some of these updates to do in the new-features branch of the project."](https://github.com/Thalassicus/cep-bnw/issues/167) I believe the minor release (stable branch) will contain smaller self-contained balance tweaks and bug fixes.

**Comment by stackpoint** [comment]
Also, all the text updates (spreadsheets) will be modified for all the policy changes all at once right before the next stable release.

**Comment by GrantSP** [comment]
I pointed @EricB1 in that direction and I believe his changes were made in an effort to help with the those specific policy changes.
If they are deemed too much, all's well and good, we can tone them back. But they did appear reasonable to me.

His input I believe will broaden our scope of what things can/may be changed.
Let's see.

**Comment by stackpoint** [comment]
The reason I closed this merge was because it was made to the wrong branch. Not because of the changes itself.

**Comment by GrantSP** [comment]
Understood. Not a problem. Just trying to help @EricB1 find his place in the scheme of things.

**Comment by stackpoint** [comment]
I don't want anybody to misunderstand my intentions here. I think @EricB1 does good work and I would actually like to try his custom version of CEP. But @Thalassicus usually is the one who gets the final word in on balance/policy changes like this and would have to be the one to merge them into the project.

**Pull request closed without merging**
