### PR TITLE
AI Flavors Overhaul

### PR DESCRIPTION
**Pull request by EricB1**
Attempt at getting the AI to have more intelligent builds (city build
orders).  Needs testing to make sure that it works.  Mainly, I want to
make the AI stop building hordes of units and bankrupting their
economies.

### CODE REVIEW

**Comment by EricB1** [comment]
Not sure why it cannot automatically merge this.  Maybe there are too many changes, or maybe it was because new files were added to the project and the solution was re-built to incorporate the new files.

**Comment by stackpoint** [comment]
I'll do the merge.

**Comment by stackpoint** [comment]
I believe I've merged the files. Take a look and test the branch to see if your changes stick.

**Comment by skodkim** [comment]
Fantastic work @EricB1 !!
Can't wait to see the result of this. unfortunately I don't have much time for CiV right now so I'll probably not be able to play test :unamused:

Follow all posts here though and it seems you're all making good progress. Lets all hope for a release soon.

**Comment by EricB1** [comment]
It looks like it's showing up in the new features branch.

I've tested it a little, but it needs a lot more.  The way to test it is just to run some all AI games using the tuner.  Just check on the AI players and see what they're building as they're playing.  Hard to get them to have "perfect" builds, but if it's somewhat reasonable and not completely stupid then that's okay.

In the past I would do this and notice them building more and more units even when they were totally bankrupt to the point that they were receiving zero science due to penalties.

If you look in the code, you'll also see that there are many more flavors than just before.  For example, building a monument does more than just have a FLAVOR_CULTURE.  It has that and a whole lot more because culture leads to policies, which leads to a variety of benefits.  Probably will need a substantial amount of tweaking to get right.

**Pull request closed without merging**
